Feat consultant offer
WildCodeSchool-2024-02/JS-RMT-Julien-Externatic-P3 pull request #12
Opened 2024-08-06 13:19 UTC by BastienDmr

2024-08-06 13:52 UTC, DylanRobinaud approved these changes

2024-08-06 13:55 UTC, DylanRobinaud submitted a review, later dismissed

2024-08-06 13:56 UTC, BertrandLrc approved these changes

2024-08-06 13:58 UTC, ITrogg submitted a review, later dismissed

2024-08-06 14:23 UTC, jujuck requested changes

2024-08-06 14:23 UTC, jujuck commented on client/src/main.jsx
> +            `/api/offersconsultant/${params.id}`
non juste `api/offers`

2024-08-06 14:23 UTC, jujuck commented on server/app/controllers/offerActions.js
> +const browseOffersByConsultant = async (req, res, next) => {
browseByConsultant

2024-08-06 14:23 UTC, jujuck commented on server/app/controllers/offerActions.js
> +    const offersByConsultant = await tables.offer.readAllConsultantOffer(
readAllByConsultant(1)

2024-08-06 14:23 UTC, jujuck commented on client/src/pages/backOffice/ConsultantLayout/BoardConsultant.jsx
> +  const formatOffers = offers.map((offer) => ({
A faire dans le controller

2024-08-07 09:15 UTC, lub04 approved these changes

2024-08-07 09:22 UTC, OrestiHoxhallari approved these changes

2024-08-07 09:28 UTC, jujuck approved these changes

2024-08-07 09:28 UTC, merged