link offres et boards
WildCodeSchool-2024-02/JS-RMT-Julien-Externatic-P3 pull request #17
Opened 2024-08-07 10:02 UTC by BertrandLrc

Link to offres to offer details
Link to board entreprises vers entreprise details
Link to board consultants vers consultant details
Creation du path consultant/:id et du composant DetailsConsultant

2024-08-07 10:06 UTC, OrestiHoxhallari submitted a review, later dismissed

2024-08-07 12:19 UTC, lub04 submitted a review, later dismissed

2024-08-07 12:20 UTC, ITrogg submitted a review, later dismissed

2024-08-07 14:15 UTC, BastienDmr submitted a review, later dismissed

2024-08-07 14:15 UTC, DylanRobinaud approved these changes

2024-08-08 06:48 UTC, jujuck requested changes

2024-08-08 06:48 UTC, jujuck commented on client/src/components/frontOffice/OfferCard/OfferCard.jsx
> +        <ButtonComponent
PAs de bouton dans un lien. Un bouton est prévu pour mettre en place une logique JS ou de requete. Un lien est prévu en HTML pour la navigation

2024-08-08 12:20 UTC, BastienDmr approved these changes

2024-08-08 14:12 UTC, merged