Mise en place du template pour la page d'acceuil
WildCodeSchool-2024-02/JS-RMT-Julien-Externatic-P3 pull request #20
Opened 2024-08-08 12:19 UTC by BastienDmr

2024-08-08 12:49 UTC, BertrandLrc submitted a review, later dismissed

2024-08-08 12:57 UTC, DylanRobinaud approved these changes

2024-08-09 09:13 UTC, BertrandLrc approved these changes

2024-08-09 09:23 UTC, OrestiHoxhallari approved these changes

2024-08-09 09:45 UTC, jujuck requested changes

2024-08-09 09:45 UTC, jujuck commented on client/src/main.jsx
> +          const response = await connexion.get("/api/users/consultants3");
api/users?type=candidat&limit=3

2024-08-19 13:37 UTC, DylanRobinaud submitted a review, later dismissed

2024-08-19 13:38 UTC, BertrandLrc approved these changes

2024-08-19 15:41 UTC, kpeset requested changes

2024-08-19 15:41 UTC, kpeset commented on client/src/components/UI/ShowElement/ShowElement.jsx
> +function ShowElement({ data }) {
Renommer le nom de la prop pourrait être pas mal !

2024-08-19 15:50 UTC, kpeset approved these changes

2024-08-19 15:51 UTC, BertrandLrc approved these changes

2024-08-19 15:57 UTC, lub04 approved these changes

2024-08-20 11:55 UTC, merged