Feature afficher toutes les offres
WildCodeSchool-2024-02/JS-RMT-Julien-Externatic-P3 pull request #3
Opened 2024-07-11 15:10 UTC by BertrandLrc

Feature afficher toutes les offres :

Route et requête SQL Backend
Recup data en Front / .map / composant card
CSS + responsiv (390px * 844px)

Autres :
Création fichier connexion.js dans le dossier services du front pour utiliser axios en instance.
Création des classnames pour les titres dans le App.css avec modifications de certaines variables (font size)

2024-07-12 07:38 UTC, DylanRobinaud submitted a review, later dismissed
Coté css c'est ok

2024-07-12 07:43 UTC, BastienDmr submitted a review, later dismissed

2024-07-12 07:43 UTC, lub04 submitted a review, later dismissed

2024-07-12 07:44 UTC, DylanRobinaud submitted a review, later dismissed

2024-07-12 08:26 UTC, jujuck requested changes

2024-07-12 08:26 UTC, jujuck commented on client/src/pages/Offers.jsx
> +import "../App.css";
Pas d'import de App.css, dispo en globale

2024-07-12 08:26 UTC, jujuck commented on client/src/pages/Offers.jsx
> +    <>
utilise une balise main

2024-07-12 08:26 UTC, jujuck commented on server/app/controllers/offerActions.js
> +    res.json(offers);
Précise le status 200

2024-07-12 09:55 UTC, DylanRobinaud approved these changes

2024-07-12 10:08 UTC, DylanRobinaud submitted a review, later dismissed

2024-07-12 10:16 UTC, lub04 submitted a review, later dismissed

2024-07-12 10:36 UTC, BastienDmr submitted a review, later dismissed

2024-07-12 12:12 UTC, jujuck commented on client/src/components/OfferCard.jsx
> +      <section className="section-loc">
Faire un composant pour cela, car c'est un ensemble qui est utilisé à plusieurs endroits dans l'app. Je vois 3 props, l'icone, le texte et la class css (est il possible de la diviser en 2 class: une généralité et une spécifique ) ?

2024-07-30 14:15 UTC, ITrogg submitted a review, later dismissed

2024-07-30 14:27 UTC, lub04 approved these changes

2024-07-30 14:28 UTC, BastienDmr approved these changes

2024-07-30 14:49 UTC, DylanRobinaud submitted a review, later dismissed

2024-07-30 14:59 UTC, lub04 submitted a review, later dismissed

2024-07-30 14:59 UTC, BastienDmr submitted a review, later dismissed

2024-07-30 14:59 UTC, ITrogg submitted a review, later dismissed

2024-07-31 09:18 UTC, DylanRobinaud approved these changes

2024-07-31 09:19 UTC, BastienDmr approved these changes

2024-07-31 09:19 UTC, OrestiHoxhallari approved these changes

2024-07-31 09:23 UTC, jujuck approved these changes

2024-07-31 09:23 UTC, merged