Feat login
WildCodeSchool-2024-02/JS-RMT-Julien-Externatic-P3 pull request #34
Opened 2024-08-21 14:34 UTC by BertrandLrc

2024-08-21 15:01 UTC, ITrogg submitted a review, later dismissed

2024-08-21 15:05 UTC, OrestiHoxhallari submitted a review, later dismissed

2024-08-27 08:28 UTC, BastienDmr submitted a review, later dismissed

2024-08-27 08:51 UTC, lub04 submitted a review, later dismissed

2024-08-27 09:13 UTC, jujuck requested changes

2024-08-27 09:13 UTC, jujuck commented on server/app/controllers/authActions.js
> +        .json(jwt.verify(token, APP_SECRET));
json(user) (Attention, vérification de la récupération en Front)

2024-08-27 09:13 UTC, jujuck commented on server/app/routers/api/router.js
> +router.use("/login", usersRouter);
Revoir les routes en globale
users/
users/signup
users/login
Attention mets le front à jour

2024-08-27 09:13 UTC, jujuck commented on server/app/routers/api/users/router.js
> +router.post("/mail", authActions.login);
A décliner les routes

2024-08-27 10:14 UTC, lub04 approved these changes

2024-08-27 10:18 UTC, jujuck approved these changes

2024-08-27 10:18 UTC, merged