BackEnd Modify profil
WildCodeSchool-2024-02/JS-RMT-Julien-Externatic-P3 pull request #6
Opened 2024-07-30 14:57 UTC by OrestiHoxhallari

2024-07-30 15:01 UTC, lub04 submitted a review, later dismissed

2024-07-30 15:01 UTC, DylanRobinaud approved these changes

2024-07-30 15:02 UTC, BertrandLrc approved these changes

2024-07-30 15:02 UTC, BastienDmr submitted a review, later dismissed

2024-07-30 15:08 UTC, ITrogg approved these changes

2024-07-30 15:13 UTC, DylanRobinaud approved these changes

2024-07-30 15:13 UTC, BertrandLrc submitted a review, later dismissed

2024-08-02 09:45 UTC, DylanRobinaud approved these changes

2024-08-02 10:12 UTC, BertrandLrc approved these changes

2024-08-02 10:13 UTC, lub04 approved these changes

2024-08-02 10:44 UTC, lub04 approved these changes

2024-08-02 12:57 UTC, DylanRobinaud approved these changes

2024-08-02 12:58 UTC, lub04 approved these changes

2024-08-03 10:35 UTC, ITrogg commented on client/src/components/formProfil/UI/buttonComponent.jsx
Le type aussi doit être en props, on a des bouttons qui ne seront pas des submit

2024-08-03 10:48 UTC, ITrogg commented on client/src/components/formProfil/UI/DescriptionComponent.jsx
Pas de label ???

2024-08-03 10:51 UTC, ITrogg commented on client/src/components/formProfil/UI/InputComponent.jsx
Le label est inutile là, HTLMfor + id. On pense à l'accessibilité

2024-08-03 10:51 UTC, ITrogg requested changes
Y'a pas que le formulaire de profil sur le site. Les composants de formulaire peuvent être dans le dossier UI gnrl voir UI/form . 

DescriptionComponent ? Pk pas TextArea tout simplement ?

2024-08-03 18:07 UTC, BertrandLrc commented on client/src/components/formProfil/UI/buttonComponent.jsx
je suis d'accords faut créer une props pour le type

2024-08-05 07:01 UTC, lub04 commented on client/src/components/formProfil/UI/buttonComponent.jsx
ESlint ne laisse pas passer les types en dynamiques il faudra faire un ternaire pour changer le type

2024-08-06 13:44 UTC, lub04 approved these changes

2024-08-06 13:44 UTC, BertrandLrc approved these changes

2024-08-06 14:05 UTC, jujuck approved these changes

2024-08-06 14:06 UTC, merged